### ISSUE TITLE
Please support bleve/v2

### ISSUE THREAD

**Issue by suntong** [leopku/bleve-gse-tokenizer#2]
Following up from https://github.com/leopku/bleve-gse-tokenizer/issues/1#issuecomment-760655622

> add import bleve-gse-tokenizer: `_ "github.com/leopku/bleve-gse-tokenizer"`
> 
> ```go
> import (
> 	"fmt"
> 	"os"
> 
> 	"github.com/blevesearch/bleve"
> 	_ "github.com/leopku/bleve-gse-tokenizer"
> )
> ```

It works fine until I added `/v2` after bleve, to:

`	"github.com/blevesearch/bleve/v2"
`

Now it error again, with 

`panic: no tokenizer with name or type 'gse' registered
`

Please support bleve/v2. Thx!

**Comment by leopku** [comment]
Sorry for being busy for another project.
V2 supporting need review changes of bleve, I'm afraid no time to do this recently.

But PRs are always welcome.
Would you plz help me to make v2 supporting, @suntong ?

**Comment by leopku** [comment]
Thank you @suntong .
But after thinking carefully, I will revert merging of master instead of creating a new v2 branch to keep back compatible.

**Comment by suntong** [comment]
OK. it's your repo and your decsion.

**Comment by leopku** [comment]
I'm now testing not reverting by creating a new v1 branch.

**Comment by leopku** [comment]
Done by 4bbadca .
Now master branch supports v2. See readme to see how to use.

Legacy v1 version was in [v1](../tree/v1) branch.

Feel free to reopen this issue for questions.

**Comment by suntong** [comment]
Yeah, creating a new v1 branch is a better option! 
Thumbs up! :+1: :+1:
