### ISSUE TITLE
Not always work

### ISSUE THREAD

**Issue by suntong** [leopku/bleve-gse-tokenizer#3]
This is the program that I tried:

```go
package main

import (
	"fmt"
	"os"

	"github.com/blevesearch/bleve"
	_ "github.com/leopku/bleve-gse-tokenizer"
)

func main() {
	INDEX_DIR := "bleve.gse"
	message := "工信处女干事每月经过下属科室都要亲口交代24口交换机等技术性器件的安装工作"

	mapping := bleve.NewIndexMapping()
	os.RemoveAll(INDEX_DIR)
	defer os.RemoveAll(INDEX_DIR)

	if err := mapping.AddCustomTokenizer("gse", map[string]interface{}{
		"type":       "gse",
		"user_dicts": "",
	}); err != nil {
		panic(err)
	}
	if err := mapping.AddCustomAnalyzer("gse", map[string]interface{}{
		"type":      "gse",
		"tokenizer": "gse",
	}); err != nil {
		panic(err)
	}
	mapping.DefaultAnalyzer = "gse"

	index, err := bleve.New(INDEX_DIR, mapping)
	if err != nil {
		panic(err)
	}
	if err := index.Index("1", message); err != nil {
		panic(err)
	}

	query := "干事"
	req := bleve.NewSearchRequest(bleve.NewQueryStringQuery(query))
	req.Highlight = bleve.NewHighlight()
	res, err := index.Search(req)
	if err != nil {
		panic(err)
	}
	fmt.Printf("Result of: '%s': %d matches\n", query, res.Total)
	for i, hit := range res.Hits {
		rv := fmt.Sprintf("%d. %s, (%f)\n", i+res.Request.From+1, hit.ID, hit.Score)
		for fragmentField, fragments := range hit.Fragments {
			rv += fmt.Sprintf("%s: ", fragmentField)
			for _, fragment := range fragments {
				rv += fmt.Sprintf("%s", fragment)
			}
		}
		fmt.Printf("%s\n", rv)
	}

	index.Close()
}
```

It suppose to mach but it prints 0 matches.

Thanks

**Comment by suntong** [comment]
proof is at:

https://github.com/leopku/bleve-gse-tokenizer/blob/676160f93197e4a0e7813301d4c6cfc036ff2699/bleve_test.go#L97-L147

**Comment by suntong** [comment]
query := "干事" still has 0 matches. 

The problem is not fixed. 
Please reopen. thx

**Comment by suntong** [comment]
The panic actually makes it works. It was working before without the dictionary. and query := "干事" can have 1 match in that case, which is better than using the dictionary.

**Comment by suntong** [comment]
Moreover, I took a look at 5c7fd47, and it seems to me that `config["user_dicts"]` is now enforced with a `panic`, but it is actually never used anywhere. Only enforced, never used. which concurs with my saying, _"gse will work even without a custom dictionary"_.

**Comment by leopku** [comment]
> Moreover, I took a look at [5c7fd47](https://github.com/leopku/bleve-gse-tokenizer/commit/5c7fd478a484dc272909975a8d8f6ec08b6fc549), and it seems to me that `config["user_dicts"]` is now enforced with a `panic`, but it is actually never used anywhere. Only enforced, never used. which concurs with my saying, _"gse will work even without a custom dictionary"_.

There are two point:
1.  `config["user_dicts"]` was very useful for loading dicts but NOT never used while init. Review the codes plz.
2. Gse would auto load its own dicts by default. But in binary release mode and run binary in a clean machine which not Gse installed, it would throw an warning of `Could not load dictionaries`.

AS two points above, I decided to enforce specifying config["user_dicts"].

**Comment by leopku** [comment]
> query := "干事" still has 0 matches. See
> 
> https://github.com/leopku/bleve-gse-tokenizer/blob/676160f93197e4a0e7813301d4c6cfc036ff2699/bleve_test.go#L101
> 
> The problem is not fixed.
> Please reopen. thx

Results of test case in my machine,
```
=== RUN   TestSearch
Search of: '干事亲口交待' matched
Search of: '干事' matched
Search of: '女干事' matched
Search of: '事亲' matched
Search of: '亲口' matched
Search of: '口交' matched
Search of: '交待' matched
Search of: '口交待' matched
Search of: '亲口交待' matched
Search of: '工信交待' matched
Search of: '干事交待' matched
Search of: '干事亲口' matched
Search of: '干事亲口交待' matched
Search of: '每月经过' matched
Search of: '每月交代' matched
Search of: '每月技术' matched
Search of: '安装技术' matched
--- PASS: TestSearch (0.96s)
PASS
ok  	github.com/leopku/bleve-gse-tokenizer/v2	0.987s
```

**Comment by suntong** [comment]
> config["user_dicts"] was very useful for loading dicts but NOT never used while init. Review all the codes plz.

I don't know the code but I did review the code over and over before asking the question. It would be helpful if you could elaborate how and where it is used. thx. 

> Search of: '干事' matched

Please take a closely look at the test code and try to understand what does that "matched" really means, and why I put "???!" with that _"match"_

**Comment by leopku** [comment]
@suntong 

Plz see this line in https://github.com/leopku/bleve-gse-tokenizer/blob/70c4b710d4aa3a779d8abf7224aba32a1979ddd7/tokenizer.go#L23
```
segmenter.LoadDict(dictFiles)
```

Does it means `it is actually never used anywhere` ???

**Comment by suntong** [comment]
Why it need two parameters before?

https://github.com/leopku/bleve-gse-tokenizer/blob/4c01f29184abf5def985404093048db6ccf0ff00/tokenizer.go#L23

**Comment by suntong** [comment]
https://github.com/leopku/bleve-gse-tokenizer/blob/3b531e374917a1d7841d8e3c15107b74a2487d74/bleve_test.go#L101

This means that the word "干事" ***cannot be found*** by `bleve.NewSearchRequest`, and same is this:

https://github.com/leopku/bleve-gse-tokenizer/blob/3b531e374917a1d7841d8e3c15107b74a2487d74/bleve_test.go#L116

**Comment by leopku** [comment]
Hi @suntong , this repo just provides a wrapper of gse for bleve search engine.
Issues of accurate of word segments etc, please referer [original issue list of gse](https://github.com/go-ego/gse/issues)

**Comment by suntong** [comment]
That's a good point, will redirect query there. thx

**Comment by leopku** [comment]
You are welcome.
