### ISSUE TITLE
Dict file is not necessary

### ISSUE THREAD

**Issue by fy0** [leopku/bleve-gse-tokenizer#7]
Just use text like "zh, jp" is ok.

**Comment by leopku** [comment]
Thanks for mention.
I will fix it after testing.

**Comment by fy0** [comment]
@leopku Wait! Seems it's load from GOPATH, and my program crashed on another device:

2022/03/16 19:23:02 Could not load dictionaries: "github.com/go-ego/gse@v0.70.0/data/dict/zh/t_1.txt", open github.com/go-e
go/gse@v0.70.0/data/dict/zh/t_1.txt: no such file or directory

btw: gse takes lot of memory, is any way to reduce memory usage?

**Comment by leopku** [comment]
Right. App would be crashed if binary file was deployed to another device.

For memory usage, my suggestion is making the function as a service alone.

**Comment by leopku** [comment]
Closed as it seems not a problem.

Feel free to reopen for any questions.
